version: '3.8'

services:
  bot:
    container_name: bot
    build: .
    depends_on:
      - auth
      - redis
    env_file:
      - .env
    volumes:
      - .:/bot
    restart: always
    networks:
      - knowledge_keeper_network
  auth:
    container_name: auth
    build: ./auth_server
    volumes:
      - ./auth_server:/auth
    ports:
      - 5000:5000
    restart: always
    networks:
      - knowledge_keeper_network
  redis:
    container_name: redis
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - 6380:6379
    command: redis-server --save 20 1 --requirepass knowledge_bot_redis_password
    volumes:
      - .redis_data:/data
    networks:
      - knowledge_keeper_network
      
networks:
  knowledge_keeper_network: 
    name: knowledge_keeper_network
