from enum import Enum


class CallbackOperation(Enum):
    GET_RECORD_BY_ID = 1
    SEARCH_RECORDS_BY_TITLE_SWITCH_PAGE = 2
    GET_ALL_RECORDS_SWITCH_PAGE = 3
    GET_RECORDS_BY_TOPIC = 4
    GET_RECORDS_BY_TOPIC_SWITCH_PAGE = 5
    CANCEL = 6
    UPDATE_RECORD = 7
    DELETE_RECORD = 8
    GET_RECORDS_BY_SUBTOPIC = 9
    GET_RECORDS_BY_SUBTOPIC_SWITCH_PAGE = 10
    GET_SUBTOPICS = 11
